version: "3.8"

services:
  video-automation:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
      - ./temp:/usr/src/app/temp
      - ./output:/usr/src/app/output
      - ./data:/usr/src/app/data
      - ./assets:/usr/src/app/assets
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:10000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
